<script src="{{ asset('assets/js/jquery-3.6.0.min.js') }}"> </script>
<script src="{{ asset('assets/js/popper.min.js') }}"> </script>
<script src="{{ asset('assets/js/bootstrap.min.js') }}"> </script>
<script src="{{ asset('assets/fontawesome/all.min.js') }}"> </script>
<script src="{{ asset('assets/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('assets/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('assets/js/dataTables.buttons.min.js') }}"></script>
<script src="{{ asset('assets/js/select2.full.min.js') }}" ></script>
<script src="{{ asset('assets/js/inputmask.js') }}" ></script>
<script src="{{ asset('assets/js/inputmask.js') }}" ></script>
<script src="{{ asset('assets/summernote/summernote-bs4.js') }}" ></script>
<script src="{{ asset('assets/js/dropzone-config.js') }}" ></script>
<script src="{{ asset('assets/js/dropzone.js') }}" ></script>
<script src="https://unpkg.com/xregexp@5.0.2/xregexp-all.js" ></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/xregexp/3.2.0/xregexp-all.min.js"></script>
